[package]
name = "oxide_gambit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engine = { path = "engine" } 

[workspace]
members = [
    "proc_macros",
    "engine",
]
