[package]
name = "oxide-gambit"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version="0.8.1", features=["dynamic"] }
# bevy = "0.8.1"
iyes_loopless = "0.8.0"
bevy-inspector-egui = "0.13.0"
bevy_prototype_debug_lines = "0.8.1"

lazy_static = "1.4.0"
futures-lite = "1.11.3"
anyhow = "1.0.66"

server = { path = "server" }

[profile.release]
overflow-checks = true

[workspace]
members = [
    "server",
]