[package]
name = "engine"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
crossterm = "0.26.1"
ctor = "0.1.26"
derive_more = "0.99.17"
proc_macros = { path = "../proc_macros" }
rustc-hash = "1.1.0"
strum = "0.24.1"
strum_macros = "0.24.3"
